apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: block-log4shell
spec:
  hosts:
  - "*"
  gateways:
  - todolist
  http:
  - route:
    - destination:
        host: todolist.default.svc.cluster.local
        port:
          number: 80
