apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: block-log4shell-in-mesh
spec:
  hosts:
  - "*"
  http:
  - match:
    - headers:
        user-agent:
          regex: ".*\$\{jndi:.*"
      uri:
        regex: ".*\$\{jndi:.*"
    directResponse:
      status: 503
  - route:
    - destination:
        port:
          number: 80
        host: todolist.default.svc.cluster.local
